---
title: "Week 3 Notes - Course Introduction"
date: "2025-09-08"
---

## Key Concepts Learned
- [List main concepts from lecture]
- [Technical skills covered]
quiz 3 questions
algorithmic decision making rely on proxy because some data is difficult to collet
CENSUS counts everyone,ACS has margins of error
decision making appealing to government because convenient
anscommbe's quartet
bad visualilzation have real consequences
ggplot2 philosophy

find median age

left join and right join


## Coding Techniques
- [New R functions or approaches]
- [Quarto features learned]
g<-ggplot(data=gcs_data)+aes(x=income,y=%bach ,color=%happy)+geom_points(decorate   colors,sizes)+x_xaxis

g <- ggplot(data = gcs_data) +
     aes(x = income, y = `%bach`, color = `%happy`) +
     geom_point(size = 3) +
     xlab("Income") +
     ylab("Bachelor %") +
     labs(color = "Happiness %")

fill:area fill color
alpha:transparent

## Questions & Challenges
- [What I didn't fully understand]
- [Areas needing more practice]

## Connections to Policy
- [How this week's content applies to real policy work]

## Reflection
- [What was most interesting]
- [How I'll apply this knowledge]
